version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgresql_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: serg3502873/foodgram-backend:latest
    restart: always
    volumes:
      - static_value:/app/static-backend/
      - media_value:/app/media-backend/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: serg3502873/foodgram-frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./foodgramproject.crt:/etc/nginx/foodgramproject.crt
      - ./foodgramproject.key:/etc/nginx/foodgramproject.key
      - ../frontend/build:/usr/share/nginx/html/
      - static_value:/var/html/static-backend/
      - media_value:/var/html/media-backend/
      #- redoc:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
    restart: always


volumes:
  postgresql_value:
  static_value:
  media_value: